### PR TITLE
Fixing build

### PR DESCRIPTION
**Pull request by NinadKavimandan**

### CODE REVIEW

**Comment by bishal-pdMSFT** [comment]
why so many commits are showing up?

**Comment by NinadKavimandan** [comment]
> why so many commits are showing up?

I added a new remote, as this repo, to the existing branch which had origin as forked repo earlier. So this entire branch was pushed from start because of that. Although the difference from master is not these many commits, can it be the case that after changing the remote it changed commit ids?

**Comment by bishal-pdMSFT** [comment]
> > why so many commits are showing up?
> 
> I added a new remote, as this repo, to the existing branch which had origin as forked repo earlier. So this entire branch was pushed from start because of that. Although the difference from master is not these many commits, can it be the case that after changing the remote it changed commit ids?

yeah, better start with a new clone

**Review by bishal-pdMSFT — APPROVED** [review]

**Comment by NinadKavimandan** [comment]
Yes. Thanks!

**Pull request merged**
