### PR TITLE
Release changes for 1.2.2

### PR DESCRIPTION
**Pull request by kanika1894**
Updating changelog and package.json

Release for following issue 
client caching issue 
https://github.com/microsoft/vscode-deploy-azure/pull/202

Bug in azure pipeline with github repo
https://github.com/microsoft/vscode-deploy-azure/pull/200

### CODE REVIEW

**Comment by vineetmimrot** [comment]
@tiwarishub  Can you please paste PR links, which will go with this release.

**Review by vineetmimrot — APPROVED** [review]
I assume @bishal-pdMSFT has given Green signal for this release.

**Comment by bishal-pdMSFT** [comment]
> I assume @bishal-pdMSFT has given Green signal for this release.

Yes I am aware if this @vineetmimrot . We should go ahead with vsix validation, but should we hold on to releasing to marketplace as it is gonna be long weekend. We should ship on Monday.

**Pull request merged**
