### PR TITLE
Moving simple webapp and python to remote provisioning

### PR DESCRIPTION
**Pull request by tiwarishub**
This PR is basically to move the simple application and python web app flows to remote provisioning service. Our provisioning supports all things requires for simple application and the python one was already added by Vivek.

### CODE REVIEW

**Comment by tiwarishub** [comment]
@ashwinsangem  / @anuragc617  Please review this PR.

**Comment by bishal-pdMSFT** [comment]
@kanika1894 please review this PR

**Review by kanika1894 — COMMENTED** [review]
Does this imply that remote provisioning will support webapps for all languages?
Also, can you please add PR description.

**Comment by tiwarishub** [comment]
> Does this imply that remote provisioning will support webapps for all languages?
> Also, can you please add PR description.

I didn't understand, I think simple app workflow doesn't vary based on languages. Please let me know if my understanding is wrong.

**Comment by kanika1894** [comment]
> > Does this imply that remote provisioning will support webapps for all languages?
> > Also, can you please add PR description.
> 
> I didn't understand, I think simple app workflow doesn't vary based on languages. Please let me know if my understanding is wrong.

I don't clearly remember the scenarios related to simple webapp. It will be great if you can debug and cross - check that it doesn't break any existing scenario.

**Comment by tiwarishub** [comment]
> mber

Yes @kanika1894 , i tried multiple language scenarios it was working

**Review by kanika1894 — APPROVED** [review]

**Pull request merged**
